<!-- Google Code for eCommerce  -->
<script>
    /* <![CDATA[ */

	ga('ecommerce:addTransaction', {
		'id': '<?php echo $block->getOrderId();?>',                     // Transaction ID. Required.
		'affiliation': '<?php echo $block->getOrderStoreName(); ?>',   // Affiliation or store name.
		'revenue': '<?php echo $block->getGrandTotal();?>',               // Grand Total.
		'shipping': '<?php echo $block->getShippingAmount();?>',                  // Shipping.
		'tax': '<?php echo $block->getTaxAmount();?>'                     // Tax.
	});

	<?php foreach($block->getOrderItems() as $orderItem):?>
	ga('ecommerce:addItem', {
		'id': '<?php echo $block->getOrderId();?>',                     // Transaction ID. Required.
		'name': '<?php echo $block->cleanUpValue($orderItem->getName());?>',    // Product name. Required.
		'sku': '<?php echo $orderItem->getSku();?>',                 // SKU/code.
		'price': '<?php echo $orderItem->getPrice();?>',                 // Unit price.
		'quantity': '<?php echo $orderItem->getQtyOrdered();?>'                   // Quantity.
	});
	<?php endforeach; ?>

	ga('ecommerce:send');
	ga('second.ecommerce:send');


	/* ]]> */
</script>
<!-- END Google Code for eCommerce  -->
